var openKVURL = "http://api.openkeyval.org/";

/**
 * Create a Point suitable to be stored in the PointStore
 */
function Point(lat, lon, name, tags) {
  this.lat = lat;
  this.lon = lon;
  this.name = name;
  this.tags = tags;

  /* the following members are used internally by PointStore and should not be
   * altered by the caller
   */
  this.idx = -1;
}

/**
 * Create a PointStore to store a bunch of geo points and their attributes
 *
 * Uses <a href="http://http://openkeyval.org/">open key value service.</a>
 * to persist a list of points.  Each JSON point is serialized and stored at
 * its own key.  The key name is generated by appending a number n to the
 * baseKey to form baseKey-n.  All values with keys of the form baseKey-n are
 * loaded until a 404 is returned.
 *
 * @param {string} a [hopefully] unique baseKey
 *
 * NOTE: This storage scheme suffers from ample problems that a conventional DB
 * resolves including concurrency issues between clients, no support for unique
 * base names, terrible search algorithms, etc.
 */
function PointStore(baseKey, load) {
  this.points = [];
  this.baseKey = baseKey;
  this.end = 0;
}

PointStore.prototype._getURL = function(i, store) {
  if (store)
    return openKVURL + 'store/';
  else
    return openKVURL + this.baseKey + "_" + i;
}

/**
 * load points from persistent storage
 * @param {function} function to be called after initial loading is complete
 */
PointStore.prototype.load = function(success) {
  ps = this;
  $.ajax({
    ps: ps,
    psSuccess: success,
    url: this._getURL(this.end),
    dataType: "jsonp",
    success: function(data) {
      if (!data) {
        /* in this case, we're done */
        if (this.psSuccess) {
          this.psSuccess();
        }
        return;
      }
      this.ps.points.push(JSON.parse(data));
      this.ps.end++;
      /* Recursion.  Bold.  Hopefully we won't run out of stack. */
      this.ps.load(this.psSuccess);
    }
  });
};

/**
 * get all points with a certain tag in the top-level tag member.
 *
 * @return {string} (possibly empty) list of points
 */
PointStore.prototype.getByTag = function(tag) {
};

/**
 * get complete list of points
 *
 * @return (possibly empty) list of points
 */
PointStore.prototype.getAll = function() {
  return this.points;
};

/**
 * @return number of points contained in the PointStore
 */
PointStore.prototype.length = function() {
  return this.points.length;
};

/**
 * update a point in the PointStore
 *
 * If the point does not exist in the PointStore, it will be created.
 * @param {Point} the point to update
 * @param {function} to call after the save succeeds (optional)
 */
PointStore.prototype.updatePoint = function(p, success) {
  if (p.idx == -1) {
    p.idx = this.end++;
  }
  ps = this;
  data = new Object();
  data[this.baseKey + "_" + p.idx] = JSON.stringify(p);
  $.ajax({
    ps: ps,
    psSuccess: success,
    url: this._getURL(p.idx, true),
    data: data,
    dataType: "jsonp",
    success: function(data) {
      this.ps.points.push(p);
      if (this.psSuccess) {
        this.psSuccess();
      }
    }
  });
};

/**
 * remove a point from the PointStore
 * @param {Point} the point p to remove
 */
PointStore.prototype.removePoint = function(p) {
};

/**
 * delete the entire PointStore from openkeyval
 * @param {function} to be called after deleting is complete
 */
PointStore.prototype.deletePointStore = function(done) {
  p = this.points.pop();
  if (!p) {
    this.end = 0;
    if (done)
      done();
    return;
  }
  data = new Object();
  data[this.baseKey + "_" + p.idx] = null;
  ps = this;
  psDone = done;
  $.ajax({
    ps: ps,
    psDone: done,
    url: this._getURL(p.idx, true),
    data: data,
    dataType: "jsonp",
    success: function(data) {
      this.ps.deletePointStore(psDone);
    }
  });
};
